sudo: required
services:
  - docker

before_install:
  - docker build -t testpractice -f Dockerfile.dev .

script:
  - docker run -e CI=true testpractice npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dockerpractice"
  bucket_name: "elasticbeanstalk-us-east-1-691055613509"
  bucket_path: "dockerpractice"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"